### ISSUE TITLE
problem met. working on it...

### ISSUE THREAD

**Issue by roy2020china** [limingth/xinsanban#10]
```
While downloading fourseven:scss@3.4.3...:
   error: Command failed:
   /home/zhangbing/.meteor/packages/meteor-tool/.1.4.0-1.16el7dw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
   rebuild --no-bin-links --update-binary
   module.js:327
   throw err;
   ^
   
   Error: Cannot find module '../'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.Module._load (module.js:276:25)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.<anonymous>
   (/tmp/mt-1cgp036/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-1eebsy4/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
   at Module._compile (module.js:409:26)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load (module.js:343:32)
   at Function.Module._load (module.js:300:12)
   at Function.Module.runMain (module.js:441:10)
   
   npm ERR! Linux 4.4.0-31-generic
   npm ERR! argv
   "/home/zhangbing/.meteor/packages/meteor-tool/.1.4.0-1.16el7dw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/home/zhangbing/.meteor/packages/meteor-tool/.1.4.0-1.16el7dw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
   "rebuild" "--no-bin-links" "--update-binary"
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install
   --fallback-to-build`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp
   install --fallback-to-build'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the thread-sleep
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-pre-gyp install --fallback-to-build
   npm ERR! You can get information on how to open an issue for this project
   with:
   npm ERR!     npm bugs thread-sleep
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls thread-sleep
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!
   /tmp/mt-1cgp036/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-1eebsy4/npm-debug.log
   module.js:327
   throw err;
   ^
   
   Error: Cannot find module '../'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.Module._load (module.js:276:25)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.<anonymous>
   (/tmp/mt-1cgp036/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-1eebsy4/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
   at Module._compile (module.js:409:26)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load (module.js:343:32)
   at Function.Module._load (module.js:300:12)
   at Function.Module.runMain (module.js:441:10)
   
   npm ERR! Linux 4.4.0-31-generic
   npm ERR! argv
   "/home/zhangbing/.meteor/packages/meteor-tool/.1.4.0-1.16el7dw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/home/zhangbing/.meteor/packages/meteor-tool/.1.4.0-1.16el7dw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
   "rebuild" "--no-bin-links" "--update-binary"
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install
   --fallback-to-build`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp
   install --fallback-to-build'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the thread-sleep
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-pre-gyp install --fallback-to-build
   npm ERR! You can get information on how to open an issue for this project
   with:
   npm ERR!     npm bugs thread-sleep
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls thread-sleep
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!
   /tmp/mt-1cgp036/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-1eebsy4/npm-debug.log
   
   
=> Your application has errors. Waiting for file change.

```

**Comment by roy2020china** [comment]
```
zhangbing@ThinkPad-T430:~$ cd github/xinsanban/
zhangbing@ThinkPad-T430:~/github/xinsanban$ meteor add fourseven:scss
                                                                                
Changes to your project's package version selections:
                                              
fourseven:scss  added, version 3.8.0_1        

                                              
fourseven:scss: Style with attitude. Sass and SCSS support for Meteor.js.
zhangbing@ThinkPad-T430:~/github/xinsanban$ meteor add maodouio:posts-summernote                                              
Changes to your project's package version selections:
                                              
maodouio:posts-summernote  added, version 0.0.3
natestrauser:font-awesome  added, version 4.5.0

                                              
maodouio:posts-summernote: Maodou.io posts package with summernote, A meteor
package that provides posts pages at /posts
```
```
Changes to your project's package version selections:
                                              
fourseven:scss             removed from your project
maodouio:posts-summernote  removed from your project
natestrauser:font-awesome  removed from your project

I20160804-10:34:15.268(8)? { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
W20160804-10:34:15.277(8)? (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
=> Meteor server restarted
I20160804-10:41:18.292(8)? { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
W20160804-10:41:18.313(8)? (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
=> Meteor server restarted^[[D
I20160804-10:46:22.598(8)? { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
W20160804-10:46:22.604(8)? (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
W20160804-10:46:23.398(8)? (STDERR) /home/zhangbing/.meteor/packages/meteor-tool/.1.4.0-1.16el7dw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160804-10:46:23.399(8)? (STDERR) 						throw(ex);
W20160804-10:46:23.400(8)? (STDERR) 						^
W20160804-10:46:23.400(8)? (STDERR) 
W20160804-10:46:23.400(8)? (STDERR) TypeError: Cannot read property 'ACCESS_KEY' of undefined
W20160804-10:46:23.401(8)? (STDERR)     at packages/maodouio_posts-summernote/server/config.js:2:1
W20160804-10:46:23.401(8)? (STDERR)     at packages/maodouio_posts-summernote/server/config.js:6:1
W20160804-10:46:23.402(8)? (STDERR)     at packages/maodouio_posts-summernote/server/method.js:5:1
W20160804-10:46:23.402(8)? (STDERR)     at /home/zhangbing/github/xinsanban/.meteor/local/build/programs/server/boot.js:297:10
W20160804-10:46:23.403(8)? (STDERR)     at Array.forEach (native)
W20160804-10:46:23.403(8)? (STDERR)     at Function._.each._.forEach (/home/zhangbing/.meteor/packages/meteor-tool/.1.4.0-1.16el7dw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160804-10:46:23.404(8)? (STDERR)     at /home/zhangbing/github/xinsanban/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 1
I20160804-10:46:36.726(8)? { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
W20160804-10:46:36.729(8)? (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
W20160804-10:46:37.290(8)? (STDERR) /home/zhangbing/.meteor/packages/meteor-tool/.1.4.0-1.16el7dw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160804-10:46:37.291(8)? (STDERR) 						throw(ex);
W20160804-10:46:37.291(8)? (STDERR) 						^
W20160804-10:46:37.292(8)? (STDERR) 
W20160804-10:46:37.292(8)? (STDERR) TypeError: Cannot read property 'ACCESS_KEY' of undefined
W20160804-10:46:37.292(8)? (STDERR)     at packages/maodouio_posts-summernote/server/config.js:2:1
W20160804-10:46:37.293(8)? (STDERR)     at packages/maodouio_posts-summernote/server/config.js:6:1
W20160804-10:46:37.293(8)? (STDERR)     at packages/maodouio_posts-summernote/server/method.js:5:1
W20160804-10:46:37.293(8)? (STDERR)     at /home/zhangbing/github/xinsanban/.meteor/local/build/programs/server/boot.js:297:10
W20160804-10:46:37.294(8)? (STDERR)     at Array.forEach (native)
W20160804-10:46:37.295(8)? (STDERR)     at Function._.each._.forEach (/home/zhangbing/.meteor/packages/meteor-tool/.1.4.0-1.16el7dw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160804-10:46:37.295(8)? (STDERR)     at /home/zhangbing/github/xinsanban/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 1
I20160804-10:46:50.104(8)? { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
W20160804-10:46:50.107(8)? (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
W20160804-10:46:50.681(8)? (STDERR) /home/zhangbing/.meteor/packages/meteor-tool/.1.4.0-1.16el7dw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160804-10:46:50.682(8)? (STDERR) 						throw(ex);
W20160804-10:46:50.682(8)? (STDERR) 						^
W20160804-10:46:50.682(8)? (STDERR) 
W20160804-10:46:50.683(8)? (STDERR) TypeError: Cannot read property 'ACCESS_KEY' of undefined
W20160804-10:46:50.684(8)? (STDERR)     at packages/maodouio_posts-summernote/server/config.js:2:1
W20160804-10:46:50.684(8)? (STDERR)     at packages/maodouio_posts-summernote/server/config.js:6:1
W20160804-10:46:50.684(8)? (STDERR)     at packages/maodouio_posts-summernote/server/method.js:5:1
W20160804-10:46:50.685(8)? (STDERR)     at /home/zhangbing/github/xinsanban/.meteor/local/build/programs/server/boot.js:297:10
W20160804-10:46:50.685(8)? (STDERR)     at Array.forEach (native)
W20160804-10:46:50.686(8)? (STDERR)     at Function._.each._.forEach (/home/zhangbing/.meteor/packages/meteor-tool/.1.4.0-1.16el7dw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160804-10:46:50.686(8)? (STDERR)     at /home/zhangbing/github/xinsanban/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by roy2020china** [comment]
```
Errors prevented startup:

While building the application:
error: standard-minifier-css, juliancwirko:postcss: multiple packages registered minifiers for extension "css".

Your application has errors. Waiting for file change.
```

**Comment by roy2020china** [comment]
问题解决。
```
meteor create ...
meteor add ...
git clone ...
```
