### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by roy2020china** [limingth/xinsanban#7]
### 1. error messages:
```
=> App running at: http://localhost:3000/
=> Meteor server restarted                    
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: unknown package: maodouio:meteor-image-upload
   Required by: maodouio:posts-summernote 0.0.3
   
=> Your application has errors. Waiting for file change.
^C                                            
zhangbing@ThinkPad-T430 ~/github/xinsanban $ meteor add maodouio:meteor-image-upload
 => Errors while parsing arguments:           
                                              
While adding package maodouio:meteor-image-upload:
error: no such package
```
```
zhangbing@ThinkPad-T430 ~/github/xinsanban $ meteor
[[[[[ ~/github/xinsanban ]]]]]                

=> Started proxy.                             
=> Started MongoDB.                           
maodouio:meteor-image-upload: updating npm dependencies -- qiniu...
   Determining active plugins                \

-> creating `packages.json` for the first time.
-> add your npm modules to `packages.json`

=> Creating container package for npm modules

-> npm support has been initialized.
-> please start your app again.

zhangbing@ThinkPad-T430 ~/github/xinsanban $ ^C
zhangbing@ThinkPad-T430 ~/github/xinsanban $ ^C
zhangbing@ThinkPad-T430 ~/github/xinsanban $ meteor
[[[[[ ~/github/xinsanban ]]]]]                

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While loading package fourseven:scss@3.4.3:
   error: Command failed: 
   module.js:340
   throw err;
   ^
   Error: Cannot find module '../'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (/home/zhangbing/.meteor/packages/fourseven_scss/.3.4.3.x9xgt8++os.linux.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-1ocgeve/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Function.Module.runMain (module.js:497:10)
   
   npm ERR! Linux 4.4.0-21-generic
   npm ERR! argv "node"
   "/home/zhangbing/.meteor/packages/meteor-tool/.1.3.5_1.1exvsv0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
   "rebuild" "--no-bin-links" "--update-binary"
   npm ERR! node v0.10.46
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install
   --fallback-to-build`
   npm ERR! Exit status 8
   npm ERR! 
   npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp
   install --fallback-to-build'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the thread-sleep
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-pre-gyp install --fallback-to-build
   npm ERR! You can get information on how to open an issue for this project
   with:
   npm ERR!     npm bugs thread-sleep
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls thread-sleep
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!
   /home/zhangbing/.meteor/packages/fourseven_scss/.3.4.3.x9xgt8++os.linux.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-1ocgeve/npm-debug.log
   
   module.js:340
   throw err;
   ^
   Error: Cannot find module '../'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (/home/zhangbing/.meteor/packages/fourseven_scss/.3.4.3.x9xgt8++os.linux.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-1ocgeve/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Function.Module.runMain (module.js:497:10)
   
   npm ERR! Linux 4.4.0-21-generic
   npm ERR! argv "node"
   "/home/zhangbing/.meteor/packages/meteor-tool/.1.3.5_1.1exvsv0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
   "rebuild" "--no-bin-links" "--update-binary"
   npm ERR! node v0.10.46
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install
   --fallback-to-build`
   npm ERR! Exit status 8
   npm ERR! 
   npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp
   install --fallback-to-build'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the thread-sleep
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-pre-gyp install --fallback-to-build
   npm ERR! You can get information on how to open an issue for this project
   with:
   npm ERR!     npm bugs thread-sleep
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls thread-sleep
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!
   /home/zhangbing/.meteor/packages/fourseven_scss/.3.4.3.x9xgt8++os.linux.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-1ocgeve/npm-debug.log
   
   
=> Your application has errors. Waiting for file change.
```

**Comment by roy2020china** [comment]
用mSaaS的代码跑起来了。
